baseURL = 'https://aroy1962.xyz'
languageCode = 'es'
title = 'Demasiado humano'
theme = 'ananke'

[params]
  author = 'Adriel Olórtegui Yzú'
  description = 'Reflexiones, ensayos y actos de arte humano digno de compartir'
  recent_posts_number = 5
  show_reading_time = true
  body_classes = 'avenir bg-near-white'

[menu]
  [[menu.main]]
    name = 'Inicio'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'Ensayos'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    name = 'Sobre este proyecto'
    url = '/about/'
    weight = 30
