backend:
  name: github
  repo: aroy2010/demasiado-humano
  branch: main
  base_url: https://api.github.com

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articulos"
    label: "Artículos Académicos"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Categorías", name: "categories", widget: "list"}
      - {label: "Etiquetas", name: "tags", widget: "list"}
      - {label: "Borrador", name: "draft", widget: "boolean", default: true}
      - {label: "Contenido", name: "body", widget: "markdown"}
